local T = require("lib.trade")

test("both must accept, then both confirm", function()
	local t = T.new("a", "b")
	T.set_item(t, "a", 5, 3)
	T.set_coins(t, "b", 10)
	falsy(T.confirm(t, "a"), "cannot confirm before both accepted")
	T.accept(t, "a")
	falsy(T.both_accepted(t))
	T.accept(t, "b")
	truthy(T.both_accepted(t))
	T.confirm(t, "a")
	falsy(T.ready(t))
	T.confirm(t, "b")
	truthy(T.ready(t))
end)

test("changing an offer resets accepts and confirms", function()
	local t = T.new("a", "b")
	T.accept(t, "a")
	T.accept(t, "b")
	T.confirm(t, "a")
	T.set_coins(t, "b", 1)
	falsy(t.accepted.a)
	falsy(t.accepted.b)
	falsy(t.confirmed.a)
end)

test("offers: zero removes an item, strangers are refused", function()
	local t = T.new("a", "b")
	T.set_item(t, "a", 7, 2)
	eq(#T.item_list(t, "a"), 1)
	T.set_item(t, "a", 7, 0)
	eq(#T.item_list(t, "a"), 0)
	falsy(T.set_item(t, "zed", 7, 2))
	falsy(T.set_item(t, "a", 7, -1))
	eq(T.other(t, "a"), "b")
	eq(T.other(t, "b"), "a")
end)
